# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_ts', models.DateTimeField()),
                ('event_ts_local', models.DateTimeField()),
                ('geo_lat', models.FloatField()),
                ('geo_long', models.FloatField()),
                ('altitude', models.FloatField()),
                ('vert_accuracy', models.IntegerField()),
                ('horiz_accuracy', models.IntegerField()),
                ('heading', models.FloatField()),
                ('speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TripModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_time_local', models.DateTimeField(auto_now_add=True)),
                ('end_time_local', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField()),
                ('distance', models.FloatField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tripmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UsersModel'),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UsersModel'),
        ),
    ]
