# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161210_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='password',
            field=models.CharField(default='abcd@1234', max_length=20),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('C', 'Client'), ('D', 'Driver')], default='A', max_length=20),
            preserve_default=False,
        ),
    ]
