# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20161213_0239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventsModel',
            new_name='Events',
        ),
        migrations.RenameModel(
            old_name='TripModel',
            new_name='Trips',
        ),
        migrations.RenameModel(
            old_name='UsersModel',
            new_name='Users',
        ),
    ]
