# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20161213_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_ts_local',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
